name: Build Linux Image Template
on:
  workflow_call:
    inputs:
      tags:
        type: string
        required: false
        description: "Extra tags to use besides main tag."

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: e1himself/goss-installation-action@v1.0.3
        with:
          version: 'v0.3.14'
      - name: Docker Login
        run: echo ${{ secrets.DOCKER_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Build Image
        run: docker build -t steamcmd/steamcmd:${{ env.GITHUB_JOB }} .
        working-directory: dockerfiles/${{ env.GITHUB_JOB }}
      - name: Test Image
        run: dgoss run steamcmd/steamcmd:${{ env.GITHUB_JOB }} --entrypoint=""

      # master
      - name: Tag Image
        run: >
          for TAG in ${{ inputs.tags }};
          do
            docker tag steamcmd/steamcmd:${{ env.GITHUB_JOB }} steamcmd/steamcmd:${TAG};
          done
        if: ${{ (github.ref == 'refs/heads/master') && (inputs.tags != '') }}
      - name: Push Image
        run: docker push steamcmd/steamcmd --all-tags
        if: ${{ github.ref == 'refs/heads/master' }}