name: Build Images
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 */6 * * *'

jobs:
  ## linux / ubuntu
  ubuntu-20:
    uses: ./.github/workflows/_build-linux.yml
    secrets: inherit
    with:
      tags: ubuntu latest
  ubuntu-18:
    uses: ./.github/workflows/_build-linux.yml
    secrets: inherit
  ubuntu-16:
    uses: ./.github/workflows/_build-linux.yml
    secrets: inherit

  ## linux / alpine
  alpine-3:
    uses: ./.github/workflows/_build-linux.yml
    needs: ubuntu-20
    secrets: inherit
    with:
      tags: alpine

  ## linux / rocky
  rocky-9:
    uses: ./.github/workflows/_build-linux.yml
    needs: ubuntu-20
    secrets: inherit
    with:
      tags: rocky
  rocky-8:
    uses: ./.github/workflows/_build-linux.yml
    needs: ubuntu-20
    secrets: inherit

  ## linux / centos
  centos-9:
    uses: ./.github/workflows/_build-linux.yml
    needs: ubuntu-20
    secrets: inherit
    with:
      tags: centos
  centos-8:
    uses: ./.github/workflows/_build-linux.yml
    needs: ubuntu-20
    secrets: inherit

  ## windows / default
  windows-1809:
    uses: ./.github/workflows/_build-windows.yml
    secrets: inherit
    with:
      tags: windows

  ## windows / core
  windows-core-2019:
    uses: ./.github/workflows/_build-windows.yml
    secrets: inherit
    with:
      tags: windows-core
  windows-core-1809:
    uses: ./.github/workflows/_build-windows.yml
    secrets: inherit