name: Build Images
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 */4 * * *'

jobs:
  build-ubuntu-18:
    runs-on: ubuntu-18.04
    env:
      IMAGE_TAG: "ubuntu-18"
    steps:
      - uses: actions/checkout@v2
      - uses: e1himself/goss-installation-action
      - name: Docker Login
        run: echo ${{ secrets.DOCKER_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Build Image
        run: docker build -f dockerfiles/$IMAGE_TAG -t steamcmd/steamcmd:$IMAGE_TAG .
      - name: Test Image
        run: dgoss run --entrypoint="" steamcmd/steamcmd:$IMAGE_TAG sleep 120
      - name: Tag Image
        run: for TAG in ubuntu latest; do docker tag steamcmd/steamcmd:$IMAGE_TAG steamcmd/steamcmd:${TAG}; done
      - name: Push Image
        run: for TAG in $IMAGE_TAG ubuntu latest; do docker push steamcmd/steamcmd:${TAG}; done

  build-ubuntu-16:
    runs-on: ubuntu-18.04
    env:
      IMAGE_TAG: "ubuntu-16"
    steps:
      - uses: actions/checkout@v2
      - uses: e1himself/goss-installation-action
      - name: Docker Login
        run: echo ${{ secrets.DOCKER_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Build Image
        run: docker build -f dockerfiles/$IMAGE_TAG -t steamcmd/steamcmd:$IMAGE_TAG .
      - name: Test Image
        run: dgoss run --entrypoint="" steamcmd/steamcmd:$IMAGE_TAG sleep 120
      - name: Push Image
        run: docker push steamcmd/steamcmd:$IMAGE_TAG

  build-alpine:
    runs-on: ubuntu-18.04
    needs: build-ubuntu-18
    env:
      IMAGE_TAG: "alpine"
    steps:
      - uses: actions/checkout@v2
      - uses: e1himself/goss-installation-action
      - name: Docker Login
        run: echo ${{ secrets.DOCKER_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Build Image
        run: docker build -f dockerfiles/$IMAGE_TAG -t steamcmd/steamcmd:$IMAGE_TAG .
      - name: Test Image
        run: dgoss run --entrypoint="" steamcmd/steamcmd:$IMAGE_TAG sleep 120
      - name: Push Image
        run: docker push steamcmd/steamcmd:$IMAGE_TAG

  build-busybox:
    runs-on: ubuntu-18.04
    needs: build-ubuntu-18
    env:
      IMAGE_TAG: "busybox"
    steps:
      - uses: actions/checkout@v2
      - uses: e1himself/goss-installation-action
      - name: Docker Login
        run: echo ${{ secrets.DOCKER_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Build Image
        run: docker build -f dockerfiles/$IMAGE_TAG -t steamcmd/steamcmd:$IMAGE_TAG .
      - name: Test Image
        run: dgoss run --entrypoint="" steamcmd/steamcmd:$IMAGE_TAG sleep 120
      - name: Tag Image
        run: docker tag steamcmd/steamcmd:$IMAGE_TAG steamcmd/steamcmd:lite
      - name: Push Image
        run: for TAG in $IMAGE_TAG lite; do docker push steamcmd/steamcmd:${TAG}; done

  build-centos-8:
    runs-on: ubuntu-18.04
    needs: build-ubuntu-18
    env:
      IMAGE_TAG: "centos-8"
    steps:
      - uses: actions/checkout@v2
      - uses: e1himself/goss-installation-action
      - name: Docker Login
        run: echo ${{ secrets.DOCKER_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Build Image
        run: docker build -f dockerfiles/$IMAGE_TAG -t steamcmd/steamcmd:$IMAGE_TAG .
      - name: Test Image
        run: dgoss run --entrypoint="" steamcmd/steamcmd:$IMAGE_TAG sleep 120
      - name: Tag Image
        run: docker tag steamcmd/steamcmd:$IMAGE_TAG steamcmd/steamcmd:centos
      - name: Push Image
        run: for TAG in $IMAGE_TAG centos; do docker push steamcmd/steamcmd:${TAG}; done

  build-centos-7:
    runs-on: ubuntu-18.04
    needs: build-ubuntu-18
    env:
      IMAGE_TAG: "centos-7"
    steps:
      - uses: actions/checkout@v2
      - uses: e1himself/goss-installation-action
      - name: Docker Login
        run: echo ${{ secrets.DOCKER_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Build Image
        run: docker build -f dockerfiles/$IMAGE_TAG -t steamcmd/steamcmd:$IMAGE_TAG .
      - name: Test Image
        run: dgoss run --entrypoint="" steamcmd/steamcmd:$IMAGE_TAG sleep 120
      - name: Push Image
        run: docker push steamcmd/steamcmd:$IMAGE_TAG

  build-centos-6:
    runs-on: ubuntu-18.04
    needs: build-ubuntu-18
    env:
      IMAGE_TAG: "centos-6"
    steps:
      - uses: actions/checkout@v2
      - uses: e1himself/goss-installation-action
      - name: Docker Login
        run: echo ${{ secrets.DOCKER_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Build Image
        run: docker build -f dockerfiles/$IMAGE_TAG -t steamcmd/steamcmd:$IMAGE_TAG .
      - name: Test Image
        run: dgoss run --entrypoint="" steamcmd/steamcmd:$IMAGE_TAG sleep 120
      - name: Push Image
        run: docker push steamcmd/steamcmd:$IMAGE_TAG

  build-windows-1809:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - name: Docker Login
        run: echo ${{ secrets.DOCKER_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Build Image
        run: docker build -f dockerfiles/windows-1809 -t steamcmd/steamcmd:windows-1809 .
      - name: Tag Image
        run: docker tag steamcmd/steamcmd:windows-1809 steamcmd/steamcmd:windows
      - name: Push Image
        run: docker push steamcmd/steamcmd:windows-1809
      - name: Push Image
        run: docker push steamcmd/steamcmd:windows

  build-windows-core-2019:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - name: Docker Login
        run: echo ${{ secrets.DOCKER_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Build Image
        run: docker build -f dockerfiles/windows-core-2019 -t steamcmd/steamcmd:windows-core-2019 .
      - name: Tag Image
        run: docker tag steamcmd/steamcmd:windows-core-2019 steamcmd/steamcmd:windows-core
      - name: Push Image
        run: docker push steamcmd/steamcmd:windows-core-2019
      - name: Push Image
        run: docker push steamcmd/steamcmd:windows-core

  build-windows-core-1809:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - name: Docker Login
        run: echo ${{ secrets.DOCKER_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Build Image
        run: docker build -f dockerfiles/windows-core-1809 -t steamcmd/steamcmd:windows-core-1809 .
      - name: Push Image
        run: docker push steamcmd/steamcmd:windows-core-1809
